### ISSUE TITLE
Some question about reproduce Gliner large

### ISSUE THREAD

**Issue by liuyanyi** [urchade/GLiNER#209]
Thanks for your great work, I'm trying to reproduce the result in your paper.

I observed a performance drop of approximately 5% in my trained version of GLiNER large. Below are the configuration details and datasets used for training.

<details>
  <summary>config:</summary>

  ```yaml
  # Model Configuration
  model_name: /large-storage/model/deberta-v3-large # Hugging Face model
  labels_encoder: null
  name: "span level gliner"
  max_width: 12
  hidden_size: 768
  dropout: 0.3
  fine_tune: true
  subtoken_pooling: first
  fuse_layers: false
  post_fusion_schema: "l2l-l2t-t2t"
  span_mode: markerV0
  
  # Training Parameters
  num_steps: 30000
  train_batch_size: 8
  eval_every: 5000
  warmup_ratio: 0.1
  scheduler_type: "cosine"
  
  # loss function
  loss_alpha: 0.75
  loss_gamma: 0
  label_smoothing: 0
  loss_reduction: "sum"
  
  # Learning Rate and weight decay Configuration
  lr_encoder: 1e-5
  lr_others: 5e-5
  weight_decay_encoder: 0.1
  weight_decay_other: 0.01
  
  max_grad_norm: 10.0
  
  # Directory Paths
  root_dir: span_gliner_logs
  train_data: "data/pilener_train.json" # see https://github.com/urchade/GLiNER/tree/main/data
  val_data_dir: "data/IE_INSTRUCTIONS/NER copy"
  # "NER_datasets": val data from the paper can be obtained from "https://drive.google.com/file/d/1T-5IbocGka35I7X3CE6yKe5N_Xg2lVKT/view"
  
  # Pretrained Model Path
  # Use "none" if no pretrained model is being used
  prev_path: null
  
  save_total_limit: 3 #maximum amount of checkpoints to save
  
  # Advanced Training Settings
  size_sup: -1
  max_types: 100
  shuffle_types: true
  random_drop: true
  max_neg_type_ratio: 1
  max_len: 512
  freeze_token_rep: false
  ```
</details>

<details>
  <summary>training command</summary>
  
  ```bash
  python3 train.py --config configs/config_my.yaml --log_dir ./logs_deberta
  ```

</details>

<details>
  <summary>training result</summary>
  
  ```txt
  ##############################################
  step: 20000

  Table for zero-shot benchmark
  CrossNER_AI         : 49.5%
  CrossNER_literature : 57.9%
  CrossNER_music      : 67.1%
  CrossNER_politics   : 68.7%
  CrossNER_science    : 55.4%
  mit-movie           : 50.3%
  mit-restaurant      : 36.2%
  Average             : 55.0%
  ##############################################
  
  ##############################################
  step: 30000

  Table for zero-shot benchmark
  CrossNER_AI         : 47.9%
  CrossNER_literature : 55.3%
  CrossNER_music      : 66.7%
  CrossNER_politics   : 68.6%
  CrossNER_science    : 54.6%
  mit-movie           : 50.7%
  mit-restaurant      : 37.1%
  Average             : 54.4%
  ##############################################
  ```

</details>

Could you give me some advise about the reproduce?

Also, i'm little confused about train.py and custom_train.py, is there any difference?
